services:
  tf2-quickserver:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: tf2-quickserver
    env_file:
      - .env
    volumes:
      - ./db:/app/db
      - ./config:/app/config:ro
      - ./keys:/app/keys:ro
    profiles:
      - bot
  tf2-pickup-server:
    build:
      context: ./
      dockerfile: ./variants/fat-tf2pickup/Dockerfile
    container_name: tf2-pickup-server
    env_file:
      - .env
    command:
      - "-enablefakeip"
      - "+sv_pure"
      - "2"
      - "+maxplayers"
      - "24"
      - "+map"
      - "cp_badlands"
    # NET_ADMIN capability required to set MTU inside the container for UDP fragmentation control
    cap_add:
      - NET_ADMIN
    profiles:
      - server
  fat-server-i386:
    build:
      context: ./
      dockerfile: ./variants/fat-standard-competitive-i386/Dockerfile
    container_name: tf2-fat-server-i386
    ports:
      - 27015:27015
      - 27015:27015/udp
      - 27020:27020
      - 27020:27020/udp
    env_file:
      - .env
    command:
      - "-enablefakeip"
      - "+sv_pure"
      - "2"
      - "+maxplayers"
      - "24"
      - "+map"
      - "cp_badlands"
      - +log
      - on
      - +logaddress_add
      - "host.docker.internal:27101"
    # NET_ADMIN capability required to set MTU inside the container for UDP fragmentation control
    cap_add:
      - NET_ADMIN
    profiles:
      - server
  fat-tf2center:
    build:
      context: ./
      dockerfile: ./variants/fat-tf2center/Dockerfile
    container_name: tf2-fat-tf2center
    ports:
      - 27015:27015
      - 27015:27015/udp
      - 27020:27020
      - 27020:27020/udp
    env_file:
      - .env
    command:
      - "-enablefakeip"
      - "+sv_pure"
      - "2"
      - "+maxplayers"
      - "24"
      - "+map"
      - "cp_badlands"
      - +log
      - on
      - +logaddress_add
      - "host.docker.internal:27101"
    # NET_ADMIN capability required to set MTU inside the container for UDP fragmentation control
    cap_add:
      - NET_ADMIN
    profiles:
      - server
  fat-mge-tf:
    build:
      context: ./
      dockerfile: ./variants/fat-mge-tf/Dockerfile
    container_name: tf2-fat-mge-tf
    ports:
      - 27015:27015
      - 27015:27015/udp
      - 27020:27020
      - 27020:27020/udp
    env_file:
      - .env
    command:
      - "-enablefakeip"
      - "+sv_pure"
      - "2"
      - "+maxplayers"
      - "24"
      - "+map"
      - "mge_training_v8_beta4b"
      - +log
      - on
      - +logaddress_add
      - "host.docker.internal:27101"
    # NET_ADMIN capability required to set MTU inside the container for UDP fragmentation control
    cap_add:
      - NET_ADMIN
    profiles:
      - server

  fat-casual-server-i386:
    build:
      context: ./
      dockerfile: ./variants/fat-casual-i386/Dockerfile
    container_name: tf2-fat-casual-server-i386
    ports:
      - 27015:27015
      - 27015:27015/udp
      - 27020:27020
      - 27020:27020/udp
    env_file:
      - .env
    command:
      - "-enablefakeip"
      - "+sv_pure"
      - "1"
      - "+maxplayers"
      - "24"
      - "+map"
      - "pl_badwater"
      - +log
      - on
      - +logaddress_add
      - "host.docker.internal:27101"
    # NET_ADMIN capability required to set MTU inside the container for UDP fragmentation control
    cap_add:
      - NET_ADMIN
    profiles:
      - server

  datasette:
    build:
      context: ./datasette
      dockerfile: Dockerfile
    container_name: tf2-datasette
    mem_limit: 128M
    mem_reservation: 64M
    cpus: 0.5
    volumes:
      - ./db:/db:ro
    ports:
      - "8001:8001"
    environment:
      - DATASETTE_PASSWORD=${DATASETTE_PASSWORD}
    env_file:
      - .env
    command:
      - -p
      - "8001"
      - -h
      - "0.0.0.0"
      - /db/database.sqlite3
    profiles:
      - analytics